# Generated by Django 5.0.7 on 2024-11-03 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_remove_menu_unique_menu_per_date_per_restaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='menu_photos/'),
        ),
    ]
