# Generated by Django 5.0.7 on 2024-11-03 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_menu_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='time',
            field=models.CharField(choices=[('아침', '아침'), ('중식', '중식'), ('석식', '석식')], default='중식', max_length=10),
            preserve_default=False,
        ),
    ]
