# Generated by Django 5.0.7 on 2024-11-06 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_menu_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='time',
            field=models.CharField(choices=[('조식', '조식'), ('중식', '중식'), ('석식', '석식')], max_length=10),
        ),
    ]
