# Generated by Django 5.0.7 on 2024-11-14 07:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 14, 7, 57, 35, 583717, tzinfo=datetime.timezone.utc)),
        ),
    ]
