# Generated by Django 5.0.7 on 2024-11-14 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0002_rating_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
